# StarRocks connection
# This profile is used to connect to the StarRocks database. It includes the necessary credentials and connection details.
starrocks_db:
  target: prod
  outputs:
    prod:
      type: starrocks
      host: "{{ env_var('STARROCKS_HOST') }}"
      port: "{{ env_var('STARROCKS_PORT', 9030) }}"
      schema: "{{ env_var('STARROCKS_DB', 'analytics_rme') }}"
      username: "{{ env_var('STARROCKS_USER') }}"
      password: "{{ env_var('STARROCKS_PASS') }}"
